import { SetupComet } from '@stellaria/comet';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import themes from '../themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo'
};

type Props = {
  children: React.ReactNode;
};

const RootLayout = (props: Props) => {
  const { children } = props;

  return (
    <html lang="en">
      {/* <NovaCache style_id={CONFIG.STYLE_ID} api_key={CONFIG.API_KEY} /> */}
      <body className={inter.className}>
        <SetupComet default="light" themes={themes} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
