[package]
name = "comet_compiler_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
comet_compiler = { path = "../compiler" }
wasm-bindgen = { workspace = true, features = ["enable-interning", "serde-serialize"]  }
console_error_panic_hook = "0.1.7"

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true